# Travis CI Configuration File
# http://about.travis-ci.org/docs/user/languages/php/

language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=4.1.0 WP_MULTISITE=0
    - WP_VERSION=4.0.0 WP_MULTISITE=0
    - WP_VERSION=3.9.0 WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=4.1.0 WP_MULTISITE=1
    - WP_VERSION=4.0.0 WP_MULTISITE=1
    - WP_VERSION=3.9.0 WP_MULTISITE=1

before_script:
    - composer install --no-interaction --optimize-autoloader

script: `echo test pass`

branches:
  only:
    - master
    - develop