<?php
/**
 * DO NOT EDIT THIS FILE
 *
 * Instead, edit app-config.php for changes
 */

/** The root directory that houses `wp` */
define('WP_ROOT', __DIR__);

/** Absolute path to the WordPress directory. */
if ( ! defined('ABSPATH') && ! defined('WP_CLI') ) {
    define('ABSPATH', WP_ROOT . '/wp/');
}

/** Load dependencies from composer. */
require_once WP_ROOT . '/vendor/autoload.php';

/** Loads environment vars from the .env file */
$environment_file = WP_ROOT . '/.env';
if ( ! file_exists($environment_file) ) die('Missing .env file. Please provide an .env file');
$dotenv = new Dotenv\Dotenv(WP_ROOT);
$dotenv->load();
$dotenv->required(['DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL']);

/** Load WordPress configuration settings */
require_once WP_ROOT . '/app-config.php';

/* That's all, stop editing! Happy blogging. */

/** Load the WordPress environment */
require_once ABSPATH . 'wp-settings.php';
