<?php
/**
 * DO NOT EDIT THIS FILE
 *
 * Instead, edit the config files found in the config/ directory.
 */

/** Load WordPress configuration settings */
require_once dirname(__DIR__) . '/config/app.php';

/* That's all, stop editing! Happy blogging. */

/** Load the WordPress environment */
require_once ABSPATH . 'wp-settings.php';